# Generated by Django 4.0.8 on 2022-11-01 14:56

from django.db import migrations, models
import product.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('valid', models.BooleanField(db_index=True, default=True, verbose_name='有效')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('name', models.CharField(max_length=500, verbose_name='产品名称')),
                ('name_short', models.CharField(blank=True, max_length=20, null=True, verbose_name='产品简称')),
                ('code', models.CharField(max_length=20, verbose_name='产品编码')),
                ('img', models.ImageField(blank=True, default=None, null=True, upload_to=product.models.upload_path, verbose_name='产品图片')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='产品说明')),
            ],
            options={
                'verbose_name': '产品信息',
                'verbose_name_plural': '产品信息',
                'db_table': 'product_subject',
            },
        ),
    ]
