# Generated by Django 4.0.8 on 2022-11-01 15:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubject',
            name='id',
        ),
        migrations.AddField(
            model_name='productsubject',
            name='code_num',
            field=models.CharField(default=None, max_length=20, verbose_name='产品编码'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productsubject',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='编码'),
        ),
    ]
