# Generated by Django 4.0.8 on 2022-11-02 13:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_productsubject_id_productsubject_code_num_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsubject',
            name='code_num',
        ),
        migrations.CreateModel(
            name='ProductCode',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='编码')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('valid', models.BooleanField(db_index=True, default=True, verbose_name='有效')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('code_num', models.CharField(max_length=20, unique=True, verbose_name='产品编码')),
                ('name_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productsubject', verbose_name='产品名称')),
            ],
            options={
                'verbose_name': '产品编码',
                'verbose_name_plural': '产品编码',
                'db_table': 'product_code',
            },
        ),
    ]
