# Generated by Django 4.0.8 on 2022-11-02 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_productsubject_code_num_productcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcode',
            old_name='name_id',
            new_name='project_name',
        ),
    ]
