# Generated by Django 4.0.8 on 2022-11-03 14:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_productcode_project_code_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcode',
            name='project_code_status',
            field=models.SmallIntegerField(choices=[(1, '待绑定'), (2, '待寄回'), (3, '待检测'), (4, '已检测')], default=1, verbose_name='编码状态'),
        ),
        migrations.CreateModel(
            name='ProductAddress',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='编码')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('valid', models.BooleanField(db_index=True, default=True, verbose_name='有效')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('receiver', models.CharField(max_length=20, verbose_name='收件人姓名')),
                ('receiver_phone', models.CharField(max_length=11, verbose_name='收件人电话')),
                ('addr', models.CharField(max_length=250, verbose_name='收件地址')),
                ('addr_desc', models.CharField(max_length=250, verbose_name='详细地址')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productsubject', verbose_name='产品名称')),
            ],
            options={
                'verbose_name': '产品地址维护',
                'verbose_name_plural': '产品地址维护',
                'db_table': 'product_address',
            },
        ),
    ]
