# Generated by Django 4.0.8 on 2022-11-04 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_productcode_project_code_status_productaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubject',
            name='video',
            field=models.FileField(default=None, upload_to='uploads/video/%Y/', verbose_name='采样指导视频'),
        ),
    ]
