# Generated by Django 4.0.8 on 2022-11-04 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_productsubject_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcode',
            name='project_code_status',
            field=models.SmallIntegerField(choices=[(1, '待绑定'), (2, '待寄回'), (3, '待签收'), (4, '待检测'), (4, '已检测')], default=1, verbose_name='编码状态'),
        ),
    ]
