# Generated by Django 4.0.3 on 2022-11-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_productcode_project_code_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productsubject',
            name='video',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/video/%Y/', verbose_name='采样指导视频'),
        ),
    ]
