# Generated by Django 4.0.3 on 2022-11-05 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_productsubject_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcode',
            name='report',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/report/%Y/', verbose_name='检测报告'),
        ),
        migrations.AlterField(
            model_name='productcode',
            name='project_code_status',
            field=models.SmallIntegerField(choices=[(1, '待绑定'), (2, '待寄回'), (3, '待签收'), (4, '待检测'), (4, '已完成')], default=1, verbose_name='编码状态'),
        ),
    ]
