# Generated by Django 4.0.8 on 2022-11-03 12:58

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0005_productcode_project_code_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamineUser',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='编码')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('valid', models.BooleanField(db_index=True, default=True, verbose_name='有效')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('examine_name', models.CharField(max_length=20, verbose_name='受检人姓名')),
                ('certificate_type', models.SmallIntegerField(choices=[(1, '身份证'), (2, '港澳身份证'), (3, '回乡证'), (4, '军官证'), (5, '护照')], default=1, verbose_name='证件类型')),
                ('certificate_num', models.CharField(max_length=128, verbose_name='证件号码')),
                ('phone', models.CharField(max_length=11, verbose_name='手机号码')),
                ('code_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productcode', verbose_name='产品编码')),
            ],
            options={
                'verbose_name': '受检人信息',
                'verbose_name_plural': '受检人信息',
                'db_table': 'examine_user',
            },
        ),
    ]
