# Generated by Django 4.0.8 on 2022-11-04 14:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0008_alter_productcode_project_code_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogisticsAddr',
            fields=[
                ('code', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True, verbose_name='编码')),
                ('create_time', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='修改时间')),
                ('valid', models.BooleanField(db_index=True, default=True, verbose_name='有效')),
                ('remarks', models.CharField(blank=True, max_length=500, null=True, verbose_name='备注')),
                ('addresser', models.CharField(max_length=20, verbose_name='发件人姓名')),
                ('addresser_phone', models.CharField(max_length=11, verbose_name='发件人电话')),
                ('addr', models.CharField(max_length=250, verbose_name='发件人地址')),
                ('addr_desc', models.CharField(max_length=250, verbose_name='详细地址')),
                ('addr_time', models.DateTimeField(auto_now=True, db_index=True, verbose_name='取件时间')),
                ('trade_no', models.CharField(max_length=128, verbose_name='物流单号')),
                ('project_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productcode', verbose_name='产品编码')),
                ('project_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.productsubject', verbose_name='产品名称')),
            ],
            options={
                'verbose_name': '物流表',
                'verbose_name_plural': '物流表',
                'db_table': 'logistics_addr',
            },
        ),
    ]
